#define WAVETABLE_ADDRESS_SIZE 7
#define WAVETABLE_SIZE (1 << WAVETABLE_ADDRESS_SIZE)
#define WAVETABLE_OUTPUT_BITS 8	// must not exceed size of int
#define WAVETABLE_OUTPUT_MASK ((1 << WAVETABLE_OUTPUT_BITS) - 1)
#define WAVETABLE_RANGE (double)(1 << WAVETABLE_OUTPUT_BITS)
#define PHASE_TOTAL_BITS 16
#define PHASE_INTEGER_BITS WAVETABLE_ADDRESS_SIZE
#define PHASE_FRAC_BITS (PHASE_TOTAL_BITS - PHASE_INTEGER_BITS)
#define PHASE_MASK ((1 << PHASE_TOTAL_BITS) - 1)
#define PHASE_UNIT (1 << PHASE_FRAC_BITS)
#define PHASE_FRAC_MASK ((1 << PHASE_FRAC_BITS)-1)
#define INTERP_OUTPUT_BITS 12
#define INTERP_OUTPUT_MASK ((1 << INTERP_OUTPUT_BITS) - 1) 
#define SIN_SCALE 0.99999 

#define SAMPLES_PER_CYCLE 100
#define SIGNAL_LENGTH 128
#define PHASE_INC ((WAVETABLE_SIZE * (1 << PHASE_FRAC_BITS))/SAMPLES_PER_CYCLE)
#define M_PI 3.141592653589793238462643383279502884197
